- name: FTP Deploy
  uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  with:
    server: 167.88.45.24  # FTP server
    username: arambilal  # FTP username
    password: ${{ secrets.password }}  # FTP password (stored in GitHub Secrets)
    
    # Optional configurations
    port: # Specify port if needed
    protocol: # ftp, ftps, or ftps-legacy
    
    # Local and server directories
    local-dir: # Specify local directory (must end with a trailing slash)
    server-dir: /home/arambilal/web/aramb.dev/public_html  # Server directory (must end with a trailing slash)
    
    # Deployment state tracking
    state-name: /home/arambilal/web/aramb.dev/.github-deploy-state.json
    
    # Additional options
    dry-run: false  # Set to true to simulate deployment without making changes
    dangerous-clean-slate: false  # Set to true to wipe server-dir before deployment
    exclude: # Add glob patterns to exclude files (e.g., node_modules, .git)
    log-level: standard  # Options: minimal, standard, verbose
    security: # strict or loose
    timeout: # Timeout in milliseconds for FTP operations
